name: Build backend and push Docker Image

on:
  push:
    branches:
      - dev
    paths:
      - backend/**
  pull_request:
    branches:
      - dev
    paths:
      - backend/**

defaults:
  run:
    working-directory: /backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Dart Frog
        run: dart pub global activate dart_frog_cli

      - name: Create Dev Build
        run: dart_frog build

      - name: Change Directory to build folder
        run: cd build/
